import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';

import '../../firebase_options.dart';

/// Singleton entry point for everything Firebase: lazy initialization,
/// auth, the live game-state stream, and the submitMove Cloud Function
/// callable.
///
/// Deployment status checklist (each independent — handle whichever
/// matches the plan tier you're on):
///   - `firebase_options.dart` is generated by `flutterfire configure`.
///     ✓ Already done; regenerate when adding iOS or web.
///   - Firestore security rules live in `firestore.rules` and are
///     applied via `firebase deploy --only firestore:rules`.
///   - Cloud Functions live in `functions/` and require Blaze plan.
///     Deploy with `cd functions && npm install && cd .. &&
///     firebase deploy --only functions`. Until they're deployed,
///     [submitMoveOrDirect] falls back to a direct Firestore write.
///   - Auth providers (Anonymous, Email/Password) must be enabled in
///     the Firebase Console under Build → Authentication →
///     Sign-in method.
class FirebaseService {
  FirebaseService._();
  static final instance = FirebaseService._();

  bool _initialized = false;

  FirebaseAuth get _auth => FirebaseAuth.instance;
  FirebaseFirestore get _db => FirebaseFirestore.instance;

  Future<void> ensureInitialized() async {
    if (_initialized) return;
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    _initialized = true;
  }

  /// Anonymous sign-in. Upgrade to Apple/Google later via link flow.
  Future<String> signInAnonymously() async {
    await ensureInitialized();
    final cred = await _auth.signInAnonymously();
    return cred.user!.uid;
  }

  /// Stream of the authoritative game state document.
  Stream<DocumentSnapshot<Map<String, dynamic>>> gameStream(String gameId) {
    return _db.collection('games').doc(gameId).snapshots();
  }

  /// Submit a move via the `submitMove` callable Cloud Function. The
  /// server appends the move to history and flips sideToMove atomically;
  /// see functions/src/submitMove.ts for the validation it performs.
  ///
  /// Throws if the function isn't deployed or rejects the move; callers
  /// can choose to fall back to a direct Firestore write for development
  /// on the Spark plan (see [submitMoveOrDirect]).
  Future<void> submitMove({
    required String gameId,
    required Map<String, dynamic> moveJson,
  }) async {
    await ensureInitialized();
    final callable =
        FirebaseFunctions.instance.httpsCallable('submitMove');
    await callable.call(<String, dynamic>{
      'gameId': gameId,
      'move': moveJson,
    });
  }

  /// Submit a move, preferring the Cloud Function when available and
  /// falling back to a direct Firestore append if the function isn't
  /// deployed yet. Always tries the function first so the better path
  /// becomes active automatically once deployed.
  Future<void> submitMoveOrDirect({
    required String gameId,
    required Map<String, dynamic> moveJson,
    required String nextSideToMove, // 'white' | 'black'
  }) async {
    try {
      await submitMove(gameId: gameId, moveJson: moveJson);
      return;
    } catch (e) {
      // Common reason: NOT_FOUND / Unauthenticated when functions aren't
      // deployed. Fall back to the direct write path which still passes
      // the Firestore append-only rule.
    }
    await _db.collection('games').doc(gameId).update({
      'history': FieldValue.arrayUnion([moveJson]),
      'sideToMove': nextSideToMove,
    });
  }
}
