// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZey3aoKakySz9ntjAAGKvooAwm2vB4lw',
    appId: '1:349058450896:android:4b56c86096f0c56f1065d5',
    messagingSenderId: '349058450896',
    projectId: 'five-fold-chess',
    storageBucket: 'five-fold-chess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmYVFvOX68_qSwoHgsYfPC5ksomoHIm0',
    appId: '1:349058450896:ios:de9ac839bf64eeca1065d5',
    messagingSenderId: '349058450896',
    projectId: 'five-fold-chess',
    storageBucket: 'five-fold-chess.firebasestorage.app',
    iosBundleId: 'com.fivefoldchess.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApkgvRLM0gDTe6__c0VGYxRql77KQjmbU',
    appId: '1:349058450896:web:55b02bf2b0a6bc161065d5',
    messagingSenderId: '349058450896',
    projectId: 'five-fold-chess',
    authDomain: 'five-fold-chess.firebaseapp.com',
    storageBucket: 'five-fold-chess.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmYVFvOX68_qSwoHgsYfPC5ksomoHIm0',
    appId: '1:349058450896:ios:de9ac839bf64eeca1065d5',
    messagingSenderId: '349058450896',
    projectId: 'five-fold-chess',
    storageBucket: 'five-fold-chess.firebasestorage.app',
    iosBundleId: 'com.fivefoldchess.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApkgvRLM0gDTe6__c0VGYxRql77KQjmbU',
    appId: '1:349058450896:web:800bee1242facd621065d5',
    messagingSenderId: '349058450896',
    projectId: 'five-fold-chess',
    authDomain: 'five-fold-chess.firebaseapp.com',
    storageBucket: 'five-fold-chess.firebasestorage.app',
  );

}